class Keybinds
{
    public static function fill():Array<Array<Dynamic>>
    {
        return [
			[
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_one1'))
			],
			[
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_two1')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_two2'))
			],
			[
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_three1')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_three2')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_three3'))
			],
			[
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_left')),	//SWAGGER SOULS??
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_down')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_up')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_right'))
			],
			[
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_five1')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_five2')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_five3')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_five4')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_five5'))
			],
			[
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_six1')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_six2')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_six3')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_six4')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_six5')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_six6'))
			],
			[
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_seven1')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_seven2')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_seven3')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_seven4')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_seven5')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_seven6')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_seven7'))
			],
			[
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_eight1')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_eight2')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_eight3')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_eight4')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_eight5')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_eight6')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_eight7')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_eight8'))
			],
			[
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_nine1')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_nine2')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_nine3')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_nine4')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_nine5')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_nine6')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_nine7')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_nine8')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_nine9'))
			],
			[
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_ten1')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_ten2')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_ten3')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_ten4')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_ten5')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_ten6')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_ten7')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_ten8')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_ten9')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_ten10'))
			],
			[
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_elev1')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_elev2')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_elev3')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_elev4')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_elev5')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_elev6')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_elev7')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_elev8')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_elev9')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_elev10')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_elev11'))
			],
			[
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_twel1')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_twel2')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_twel3')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_twel4')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_twel5')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_twel6')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_twel7')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_twel8')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_twel9')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_twel10')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_twel11')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_twel12'))
			],
			[
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_fort1')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_fort2')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_fort3')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_fort4')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_fort5')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_fort6')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_fort7')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_fort8')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_fort9')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_fort10')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_fort11')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_fort12')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_fort13')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_fort14'))
			],
			[
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_ate1')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_ate2')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_ate3')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_ate4')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_ate5')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_ate6')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_ate7')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_ate8')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_ate9')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_ate10')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_ate11')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_ate12')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_ate13')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_ate14')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_ate15')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_ate16')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_ate17')),
				ClientPrefs.copyKey(ClientPrefs.keyBinds.get('note_ate18')),
			]
		];
    }
}